### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by TheTrooperVB** [steverichey/DMLocalizer#11]
A game by: Un gioco di 
Powered by: Sviluppato da
Press left or right to start: Premi sinistra o destra per cominciare
Release left and right: Lascia sinistra o destra
to start: per cominciare
to erase: per cancellare
Touch left or right side to start: Tocca il lato destro o sinistro [dello schermo (if is for a Touchscreen device)]  per cominciare
Release both sides: Lascia entrambi i lati [dello schermo (if is for a Touchscreen device)]
Fill bar to erase save data: Riempi la barra per cancellare i dati salvati
Erasing save data: Cancellando i dati salvati
attempts: Tentativi
distance: Distanza
seconds: Secondi
medals: Medaglie
levels: Livelli
coins: Monete
trophies: Trofei
zenith: Zenit/Apice/Culmine
zeniths: Zenit/Apici/Culmini
the end: Fine
trophy unlocked: Trofeo Sbloccato
paused: Pausa
time: Tempo
Hold left or right to restart: Mantieni sinistra o destra per ricominciare
Touch screen to restart: Tocca lo schermo per ricominciare
Don't Move: Non Muoverti
Level Up!: Sei Salito di Livello!
Zenith:Zenit/Apice/Culmine 
Game Over: Hai Perso/Partita Finita (but it’s better to keep it in english)

Best Regards
Luca Carbone

**Comment by steverichey** [comment]
Thank you very much!

**Comment by TheTrooperVB** [comment]
It was a pleasure work a little bit on a game even only on the translation part :) I'm happy to have been helpful and in the game :D

**Comment by steverichey** [comment]
Implemented in `e8189b7d`
