### ISSUE TITLE
Finnish Translation

### ISSUE THREAD

**Issue by ghost** [steverichey/DMLocalizer#12]
A game by = Pelintekijä: (STVR)
Powered by = Tehty (HaxeFlixel) avulla
Press left or right to start = Paina vasen tai oikea nappi aloittaaksesi
Release left and right = Päästä irti vasemmasta tai oikeasta napista
to start = Aloitus
to erase = Poista
Touch left or right side to start = Kosketa vasenta tai oikeata puolta aloittaaksesi
Release both sides = Vapauta molemmat puolet
Fill bar to erase save data = Täytä palkki tallennuksen poistamiseksi
Erasing save data = Tallennettu data poistetaan 
attempts = yritykset
distance = etäisyys
seconds = sekunnit
medals = mitallit
levels = tasot
coins = kolikot
trophies = pokaalit
zenith = zeniitti
zeniths = zeniittiä
the end = loppu
trophy unlocked = pokaali saavutettu
paused = keskeytetty
time = aika
Hold left or right to restart = Paina pohjaan vasen tai oikea näppäin käynnistääksesi pelin uudelleen
Touch screen to restart = Kosketa ruutua käynnistääksesi pelin uudelleen

![dont_la](https://cloud.githubusercontent.com/assets/10381456/5622546/cc487afc-954d-11e4-92ae-622711f2888b.png)
![move_la](https://cloud.githubusercontent.com/assets/10381456/5622549/cf3abeb4-954d-11e4-8e6e-10f9ed49040f.png)
![levelup_la](https://cloud.githubusercontent.com/assets/10381456/5622550/d206dfd8-954d-11e4-9e19-8ade1ca1c5ee.png)
![zenith_la](https://cloud.githubusercontent.com/assets/10381456/5622551/d44a26ba-954d-11e4-908c-f6b84dab7db7.png)
![gameover_la](https://cloud.githubusercontent.com/assets/10381456/5622557/d601233c-954d-11e4-81a9-88a7355c7d87.png)

**Comment by steverichey** [comment]
?

**Comment by steverichey** [comment]
Thanks for this!

**Comment by steverichey** [comment]
@Mrmegacham, how would you like to be credited?

**Comment by ghost** [comment]
Yeah

**Comment by steverichey** [comment]
@Mrmegacham, what I meant was, what name should I use to credit you?

**Comment by Mrmegacham** [comment]
As: Mr.megacham, also known as Pietari Kotala

**Comment by Jormangeud** [comment]
Here are some fixes to Mrmegacham's translation.
Also, to be properly translated, I had to separate the in-game texts, see the parenthesis below.
Tested with linux-v1.3 and android-1.3.5.

A game by = Tämän pelin on tehnyt
Powered by = Pelin moottoorina

Press left or right = Paina vasemmalle tai oikealle
Release left and right to start = Vapauta vasen ja oikea aloittaaksesi
Release left and right to erase = Vapauta vasen ja oikea poistaaksesi
Fill bar to erase save data = Täytä palkki poistaaksesi tallennetut tiedot
Erasing save data = Tallennetut tiedot poistetaan
Hold left or right to restart = Pidä vasen tai oikea painettuna alas pelataksesi uudelleen

Press left or right to start = Paina vasemmalle tai oikealle aloittaaksesi
Release both sides = Vapauta molemmat puolet
Touch left or right side to start = Kosketa vasenta tai oikeata puolta aloittaaksesi
Touch screen to restart = Kosketa ruutua käynnistääksesi pelin uudelleen

(goal) attempts = yritystä
(goal) coins = kolikkoa
(goal) distance = etäisyyttä
(goal) levels = tasoa
(goal) medals = mitalia
(goal) seconds = sekuntia
(goal) trophies = pokaalia
(goal) zeniths = zeniittiä
(goal) zenith = zeniitti

(list) attempts = yritykset
(list) distance = etäisyys
(list) level = taso
(list) medals = mitalit
(list) time = aika
(list) trophies = pokaalit

(zenith) attempts = yritykset
(zenith) distance = etäisyys
(zenith) levels = tasot
(zenith) medals = mitalit
(zenith) money = raha
(zenith) time = aika
(zenith) trophies = pokaalit

trophy unlocked = pokaali saavutettu
paused = keskeytetty
the end = loppu

**Comment by steverichey** [comment]
Thanks @Jormangeud!

**Comment by steverichey** [comment]
Implemented in `8df75d83`
