### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by Godless-** [steverichey/DMLocalizer#14]
A game by: Gra stworzona przez
Powered by: Przy wsparciu
Press left or right to start: Naciśnij lewo lub prawo, by rozpocząć
Release left and right to start: Puść lewo i prawo, by rozpocząć
Release left and right to erase: Puść lewo i prawo, by usunąć
Touch left or right side to start: Dotknij lewej lub prawej strony, by rozpocząć
Release both sides: Puść obie strony
Fill bar to erase save data: Wypełnij pasek, by usunąć zapisane dane
Erasing save data: Usuwanie zapisanych danych
attempts: próby
distance: odległość
seconds: sekundy
medals: medale
level: poziom
levels: poziomów
coins: monet
trophies: trofea
zenith: zenit
zeniths: zenitów
the end: koniec
trophy unlocked: odblokowano trofeum / zdobyto trofeum
paused: pauza
time: czas
Hold left or right to restart: Przytrzymaj lewo lub prawo, by zrestartować
Touch screen to restart: Dotknij ekranu, by zrestartować

Don't Move: (I would leave the original, but if it's needed - Stój (w miejscu) / Nie ruszaj się)
Level Up!: Nowy poziom!
Zenith: Zenit
Game Over: Koniec gry

**Comment by steverichey** [comment]
Most excellent! Thank you!

**Comment by steverichey** [comment]
@Godless-, how would you like to be credited?

**Comment by Godless-** [comment]
Credit is not necessery, but if you got a spare place in the credits:
Michał "Godless" Figas
will be fine, thanks!

**Comment by steverichey** [comment]
Implemented in `6dcac643`
