### ISSUE TITLE
Hungarian Translation

### ISSUE THREAD

**Issue by maxgraham** [steverichey/DMLocalizer#16]
Okay, so we are not putting the person after the sentence every time, so like "a game by xy" we are saying "xy's game" usually.

xy will mean the unknown person/thing you will name.

A game by -> "xy játéka" 
Powered by -> "xy által készítve"  (but would be better if i know what you want to say exactly)
Press left or right to start -> "Nyomd meg a balra vagy jobbra gombot a kezdéshez"
Release left and right -> "Engedd el a balrát vagy a jobbrát"
to start -> "a kezdéshez"
to erase -> "a törléshez"
Touch left or right side to start -> "Érintsd meg a bal vagy jobb oldalt a kezdéshez"
Release both sides -> "Engedd el mind a két oldalt"
Fill bar to erase save data -> Sorry, but i don't know what you mean exactly and i don't want to say wrong thing.
Erasing save data -> "Mentett adatok törlése"
attempts -> "próbálkozások"
distance -> "távolság"
seconds -> "másodpercek"
medals -> "medálok"
levels -> "szintek"
coins -> "érmék"
trophies -> "trófeák"
zenith -> "csúcspont" (but would be better if you can describe this exactly what you mean)
zeniths -> "csúcspontok"
the end -> "vége"
trophy unlocked -> "trófea feloldva"
paused -> "megállítva"
time -> "idő"
Hold left or right to restart -> "Tartsd a balrát vagy jobbrát az újrakezdéshez"
Touch screen to restart -> "Érintsd meg a képernyőt az újrakezdéshez"

So i hope i could help you, please leave a reply what you want more, what is your problem, where you want to correct things, and i will help you.

And i want to say to the other Hungarians if they read this, correct me if i was wrong, it's not about me, it's about the game, and we want it to be the best :)

By the way i am so excited to get the game on Steam, and your game greenlit almost a year ago but nothing happened, and you just keep promising :(( 
I hope you didn't leave us alone.

**Comment by steverichey** [comment]
My game was greenlit in December, but I'm sorry for the delay. It should be available on Steam in April or early May. Thanks for the translation!

**Comment by steverichey** [comment]
Implemented in `0d7899f2`. Missing images but those can wait for later.
