### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by DanielGSM** [steverichey/DMLocalizer#3]
Language: Spanish (ES)

A game by: Un juego de
Powered by: Potenciado por
Press left or right: Pulsa izquierda o derecha
Release left and right to start: Suelta izquierda y derecha para comenzar
Release left and right to erase: Suelta izquierda y derecha para borrar
Fill bar to erase save data: Llena la barra para borrar los datos guardados
Erasing save data: Borrando datos guardados
attempts: intentos
distance: distancia
seconds: segundos
medals: medallas
level: nivel
levels: niveles
coins: monedas
trophies: trofeos
zenith: zenit/cenit/cénit[1]
zeniths: zenit/cenit/cénit[1]
the end: fin[2]
trophy unlocked: trofeo desbloqueado
paused: pausa[3]
time: tiempo
Hold left or right to restart: mantén pulsado izquierda o derecha para reiniciar
Don't Move: No te Muevas
Level Up: Subes de Nivel [4]
Game Over: Fin del Juego

Notes
[1] Zenith doesn't have plural in spanish, so both of them have exactly the same translation.
    There are also three ways of translating it: the most used ones are "cenit" and "cénit".
     I would recommend using "cenit" or "zenit", altough this last one is not very used.

[2] The literal translation would be "el fin" ("fin" would be "end"), but in spanish would be better just
      saying "fin".

[3] The literal translation would be "en pausa" ("pausa" would be "pause"). Both of them could be
     used indinstinctly, but I think "pausa" sounds better.

[4] "Subes de nivel" would be something like "you leveled up", it sounds better in spanish than
     translating exactly the original strings.

![dont_es](https://cloud.githubusercontent.com/assets/6943755/3982624/3c75e6c2-2878-11e4-898f-a82d76b4af16.png)
![move_es](https://cloud.githubusercontent.com/assets/6943755/3982626/3f773bc8-2878-11e4-80ba-0888cd2aafc9.png)
![gameover_es](https://cloud.githubusercontent.com/assets/6943755/3982629/42f06824-2878-11e4-9bc5-5270120715be.png)
![levelup_es](https://cloud.githubusercontent.com/assets/6943755/3982632/44d3e332-2878-11e4-9ff4-95524437f879.png)
![zenith_es](https://cloud.githubusercontent.com/assets/6943755/3982633/460809e0-2878-11e4-8e33-baee606a8121.png)

**Comment by steverichey** [comment]
Thanks @DanielGSM! My only comment would be on the translation for "Level Up". I can work with it, but the image is actually wider than the game screen (160 pixels). Is there a shorter translation that would work?

**Comment by DanielGSM** [comment]
Hmm... This is the shortest thing I could thought; the exact translation would be "subida de nivel", which is even longer, and doesn't even sound good.

This is one of those cases where is hard to translate the original concept in english without recurring to long and elaborated expressions.

I can only think of some workarounds, like using "nivel ↑" (this would be a really good one, if you can actually use the arrow, since it didn't work with the localizer when I tried), "nivel+", or even leaving "level up" as is, since it's one of those expressions like "start, game over, the end, etc" that everybody knows are usually are even left untranslated, but then it would be strange to translate the other strings I mentioned.

**Comment by steverichey** [comment]
Alright, I'll probably go with `nivel ↑`, even if I have to draw the arrow by hand, it's not a big deal.

**Comment by steverichey** [comment]
@DanielGSM, how would you like to be credited?

**Comment by lashermayfair** [comment]
// Correction to @Danielgsm translate of: /

Powered by: Potenciado por

// it would be better to use:

Powered by: Impulsado por

Level up translation could work in 2 lines, let me know if need anything more

![levelup_la](https://cloud.githubusercontent.com/assets/10795318/5991732/70b88cac-a9c7-11e4-9577-aa8326d9fcca.png)

**Comment by DanielGSM** [comment]
@lashermayfair I don't agree at all about the "impulsado por"; when talking about technology it's a lot more common to use "potenciado por". In fact, I have never seen "impulsado por" before, but I have seen "potenciado por" a lot of times: Potenciado por Unity, potenciado por Joomla, Potenciado por Wordpress, etc. Even the official page of Nvidia uses "potenciado por".

http://la.nvidia.com/object/tegra-zone-la.html
"potenciado por NVIDIA® Tegra™"

@steverichey just go with SillyWalk, my Steam nick, sorry for taking so long to answer.

**Comment by lashermayfair** [comment]
@danielGSM ok

**Comment by DanielGSM** [comment]
@lashermayfair The level up thing sounds fine though, better than the "nivel ↑", if the dev doesn't have any problem with the height of the text.

**Comment by steverichey** [comment]
Just so you know, the "Powered by" text is going away, as it's a bit superfluous and has caused issues with other translations as well. I'll have to text the two-line level up text, but that might be a good solution.

**Comment by steverichey** [comment]
Implemented in `c5cf7bbc`
