### ISSUE TITLE
Swedish Translation

### ISSUE THREAD

**Issue by artucino** [steverichey/DMLocalizer#4]
A game by - Ett spel skapat av
Powered by - Driftad av
Press left or right to start - Tryck vänster eller höger för att starta
Release left and right - Släpp vänster och höger
to start - för att starta
to erase - för att radera
Touch left or right side to start - Rör på vänster eller höger sida för att starta
Release both sides - Släpp båda sidorna
Fill bar to erase save data - Fyll mätaren för att radera sparad data
Erasing save data - Radera sparad data
attempts - försök
distance - distans
seconds - sekunder
medals - medaljer
levels - nivåer
coins - mynt
trophies - troféer
zenith - höjdpunkt
zeniths - höjdpunkter
the end - slut
trophy unlocked - trofé upplåst
paused - pausad
time - tid
Hold left or right to restart - Håll vänster eller höger för omstart
Touch screen to restart - Rör skärm för omstart
Don't Move - Rör dig inte
Level Up! - Nivå upp!
Game Over - Game Over

**Comment by artucino** [comment]
Game Over is widely used the same in Sweden, but I can provide with a more direct translation if that is nessesary :) 

Also, here are the images:
![dont_sv](https://cloud.githubusercontent.com/assets/8538673/4024231/d25c66cc-2bbe-11e4-95a1-d6b3fb8478c7.png)
![levelup_sv](https://cloud.githubusercontent.com/assets/8538673/4024234/db00bca6-2bbe-11e4-9b1a-c47ca9d04b1a.png)
![zenith_sv](https://cloud.githubusercontent.com/assets/8538673/4024232/d6029f80-2bbe-11e4-9a03-baed28a61873.png)
![gameover_sv](https://cloud.githubusercontent.com/assets/8538673/4024235/de4d433e-2bbe-11e4-83b7-dea9fdce5500.png)

**Comment by steverichey** [comment]
This all looks great! Thank you!

**Comment by steverichey** [comment]
@artucino, how would you like to be credited?

**Comment by artucino** [comment]
As ARTUCINO if that's okay :-)

**Comment by steverichey** [comment]
Absolutely!

**Comment by steverichey** [comment]
Implemented in `65236e2c`
