### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Pebujetti** [steverichey/DMLocalizer#5]
A game by: Игра от
Powered by: При поддержке
Press left or right: Нажмите влево или вправо
Release left and right to start: Отпустите влево и вправо для начала
Release left and right to erase: Отпустите влево и вправо для удаления
Fill bar to erase save data: Заполните полосу для удаления сохранененных данных (also can use: Удаления сохранения)
Erasing save data: Удаление сохраненных данных (also can use: Удаление сохранения)
attempts: попытки
distance: расстояние
seconds: секунды
medals: медали
levels: уровни
coins: монеты
trophies: трофеи
zenith: зенит (also can use: венец, апогей,предел)
zeniths: зенит (also can use: венец, апогей,предел)
the end: конец
trophy unlocked: трофей разблокирован
paused: пауза
time: время
Hold left or right to restart: Удерживайте влево или вправо для перезапуска
Don't Move: Не Двигайся
Level Up: Новый Уровень
Game Over: Игра Окончена

![move_la](https://cloud.githubusercontent.com/assets/8995901/4490374/82df057a-4a2a-11e4-9848-c2c52b0ae4f1.png)
![levelup_la](https://cloud.githubusercontent.com/assets/8995901/4490377/895c6cbc-4a2a-11e4-8ee6-14e5dc0107b2.png)
![zenith_la](https://cloud.githubusercontent.com/assets/8995901/4490378/8d186c98-4a2a-11e4-852e-c92061e4b84b.png)
![gameover_la](https://cloud.githubusercontent.com/assets/8995901/4490382/90d1b18c-4a2a-11e4-80c2-9a66dc4b76eb.png)

**Comment by steverichey** [comment]
Thanks for the translation!

**Comment by steverichey** [comment]
@Pebujetti, how would you like to be credited?

**Comment by Pebujetti** [comment]
Doog evening. I would like to be credited as my nickname(Pebujetti). But if
you want my full name,it's Ilia Golovkin. as you wish,thanks:)

среда, 14 января 2015 г. пользователь Steve написал:

**Comment by steverichey** [comment]
Implemented in `1fb5de30`
