### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by Tlozyx** [steverichey/DMLocalizer#7]
A game by           Een spel door
Powered by          Mede mogelijk gemaakt door
Press left or right to start        Druk op de linker of rechter pijltjestoets om te beginnen
Release left and right      Laat de rechter en linker pijltjestoets los
to start                Om te beginnen
to erase                Om te Verwijderen
Touch left or right side to start   Raak de linker or rechter pijltjestoets aan om te beginnen
Release both sides          Laat beide kanten los
Fill bar to erase save data     Vul de balk om Save games te verwijderen
Erasing save data           Save games aan het verwijderen
attempts                Pogingen
distance                Afstand
seconds             Secondes
medals              Medailles
levels              Level's
coins               Munten
trophies                Trofeeën
zenith              Zenit
zeniths             Zenit's
the end             Het Einde
trophy unlocked         Trofee Vrijgespeeld
paused              Gepauzeerd
time                Tijd
Hold left or right to restart       Druk op de linker of rechter pijltjestoets om te herstarten
Touch screen to restart     Raak de linker or rechter pijltjestoets aan om te herstarten

This is just something i made on the flow, and implementing in sentences would require some grammatical adjustments. Just let me know what you think through Steam.
EDIT:
I added the string "Save games te verwijderen" after line 9, which corrects the issue

**Comment by steverichey** [comment]
Awesome! Thank you so much!

**Comment by Tlozyx** [comment]
I noticed a slight mistake on my behalf in one of the sentences, (line 9) I'll fix it right away

**Comment by Tlozyx** [comment]
Hello, here's the request which you specified on Steam
Justin Tlozoot Post

Kind Regards,

**Comment by steverichey** [comment]
Implemented in `bb779bbc`
