### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by ghost** [steverichey/DMLocalizer#8]
Language: German/Deutsch (DE)

---Strings---

A game by: Ein Spiel von
Powered by: Angetrieben von
Press left or right: Links oder Rechts drücken
Release left and right to start: Links und Rechts loslassen, um zu starten
Release left and right to erase: Links und Rechts loslassen, um zu löschen
Fill bar to erase save data: Balken füllen, um Speicherdaten zu löschen
Erasing save data: Lösche Speicherdaten
attempts: Versuche
distance: Entfernung
seconds: Sekunden
medals: Medaillen 
levels: Level
coins: Münzen
trophies: Trophäen
zenith: Höhepunkt
zeniths: Höhepunkte
the end: das Ende
trophy unlocked: Trophäe freigeschaltet
paused: pausiert
time: Zeit
Hold left or right to restart: Links oder Rechts halten, um neuzustarten
Don't Move: Nicht Bewegen
Level Up: Levelaufstieg
Game Over: Spiel Vorbei

---Images---

DON'T:
![nicht](https://cloud.githubusercontent.com/assets/1422889/4500700/662cdc5e-4a98-11e4-95f5-8a4e0f6db47e.png)

MOVE:
![bewegen](https://cloud.githubusercontent.com/assets/1422889/4500701/6f766a28-4a98-11e4-8d5e-e0ad27489eac.png)

LEVEL UP!:
![levelaufstieg](https://cloud.githubusercontent.com/assets/1422889/4500702/7aff9eb4-4a98-11e4-8ff2-1eb928967550.png)

ZENITH:
![hohepunkt](https://cloud.githubusercontent.com/assets/1422889/4515621/0fa87ab0-4bc8-11e4-80b4-3695a8e03451.png)

GAME OVER:
![spiel vorbei](https://cloud.githubusercontent.com/assets/1422889/4500705/9640ebd8-4a98-11e4-864c-19321d44d65f.png)

**Comment by steverichey** [comment]
Thanks lordtobi!

**Comment by Treazer** [comment]
"Powered by" is actually "Unterstützt von" or "Gesponsert von". You wouldn't use "angetrieben" in that case.

**Comment by ghost** [comment]
No, that would be "Supported by" in English. "Angetrieben" is the same meaning as being "powered" by an engine, as you also "antreiben" your car with an engine.

Example:
"My car is powered by a Diesel engine."
"Mein Auto wird von einem Dieselmotor angetrieben."

**Comment by Treazer** [comment]
Yeah, that's true, but you wouldn't use that word if it's powered by a company.

**Comment by ghost** [comment]
HaxeFlixel is the engine

**Comment by steverichey** [comment]
@lordtobi, how would you like to be credited?

**Comment by ghost** [comment]
If the game has credits, make a small "Translators" section somewhere and take all of the people who helped out here.
Maybe take the real names too if the people want.

Like:
--- Translators ---
German:
    lordtobi
French:
[...]

**Comment by steverichey** [comment]
@lordtobi I'm building out the credits, but for you personally, should I use lordtobi or another name?

**Comment by ghost** [comment]
I'd prefer to have my nickname and my real name combined: Tobias 'lordtobi' Heinen

**Comment by steverichey** [comment]
Will do!

**Comment by steverichey** [comment]
Implemented in `2d125b71`
