### ISSUE TITLE
Croatian Translation

### ISSUE THREAD

**Issue by darkborn** [steverichey/DMLocalizer#9]
Language: Croatian (HR)

 Translated strings:

A game by: Igra od
Powered by: Upogonjeno od
Press left or right: Pritisni lijevo ili desno
Release left and right to start: Otpusti lijevo ili desno za početak
Release left and right to erase: Otpusti lijevo ili desno za brisanje
Fill bar to erase save data: Ispuni traku za brisanje snimljenih podataka
Erasing save data: Brisanje snimljenih podataka
attempts: pokušaja
distance: udaljenost
seconds: sekundi
medals: medalja
levels: nivoa
coins: novčića
trophies: trofeja
zenith: zenit
zeniths: zenita
the end: kraj
trophy unlocked: trofej otključan
paused: pauza
time: vrijeme
Hold left or right to restart: Drži lijevo ili desno za restart
Don't Move: Ne Mrdaj
Level Up: Viši Nivo
Game Over: Kraj Igre

Localized images:

DON'T:
![dont_hr](https://cloud.githubusercontent.com/assets/9120780/4587570/9ca97f44-502e-11e4-9dc1-74f4f8da7150.png)

MOVE:
![move_hr](https://cloud.githubusercontent.com/assets/9120780/4587637/1588ac9a-5030-11e4-9dce-adb42562dae4.png)

LEVEL UP!:
![levelup_hr](https://cloud.githubusercontent.com/assets/9120780/4587645/329e9312-5030-11e4-87e0-b70a9f750a7d.png)

ZENITH:
![zenith_hr](https://cloud.githubusercontent.com/assets/9120780/4587653/565c6838-5030-11e4-9202-811c646b0995.png)

GAME OVER:
![gameover_hr](https://cloud.githubusercontent.com/assets/9120780/4587659/6d6f4702-5030-11e4-9b03-c4352785e047.png)

**Comment by steverichey** [comment]
Thanks for your contribution!

**Comment by steverichey** [comment]
@darkborn, how would you like to be credited?

**Comment by darkborn** [comment]
As a darkborn, of course!

**Comment by steverichey** [comment]
Implemented in `4513ad98`
